name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow and custom selection toolbar and handles.
version: 10.0.1
homepage: https://github.com/fluttercandies/extended_text

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  extended_text_library:
    path: ../vb_extended_text_libaray

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


